function changeText(value) {
	if(value == "spanish")
		{
			document.getElementById("langHead").innerHTML = "Español"
			document.getElementById("langText").innerHTML = "Tú sabes, en esta ciudad, un artista realmente necesita mucho espacio cuando está tratando de crear algo especial. Un lugar para cultivar un mundo propio, lejos del mundo real que está a su alrededor. Por suerte para mí, vivo justo en el centro de la “H” de la señal de Hollywood. Y así es como paso la mayor parte de mis noches: en lo alto del caos que gira en la ciudad de los ángeles. Ahora no me malinterpreten, me encanta mojar mis dedos del pie en la tierra y mirarlos en la ciudad de vez en cuando, especialmente los martes. Pero en verdad, cuando estoy en medio de hacer un disco, sobre todo ahora, cuando el mundo está en medio de un período tumultuoso, me parece que realmente necesito tomar el espacio para mí misma lejos de la vida real, a considerar lo que “mi contribución al mundo” debe ser en estos tiempos oscuros. <br><br>Así que cada mañana, tengo el lujo de preguntarme, “¿Qué voy a cocinar para los niños de hoy? ¿Algo con un poco especial? Algo con un poco de amargura, pero es en última instancia dulce? ¿O debo tomar el día libre y bajar el fuego, y sólo tomar un momento para enviar mi amor a ellos sobre el éter? Porque a veces, simplemente ser puro de corazón y tener buenas intenciones y dejar que se conozcan es la más digna contribución que un artista puede hacer. Por lo tanto, aunque estos tiempos pueden sentirse un poco locos, no son tan diferentes de lo que otras generaciones han experimentado en un momento u otro antes. En medio de toda la incertidumbre, y como transición de una era a otra, no hay lugar mas apropiado para dar un golpe que en medio de 'Hollyweird' haciendo este disco para ti. Porque tú, y la música, y este lugar, son mi amor, mi vida, mi lujuria por la vida.";
		}
	else if(value == "english")
		{
			document.getElementById("langHead").innerHTML = "English"
			document.getElementById("langText").innerHTML = "You know, in this town, an artist really needs a lot of space when they’re trying to create something special. A place to cultivate a world of their own, far away from the real world that’s around them. Luckily for me, I live right inside the middle of the “H” of the Hollywood sign. And this is how I spend most of my nights: perched high above the chaos that swirls within the city of angels below. Now don’t get me wrong, I love to dip my toe into the muck and the mires of the city every now and then. Especially on Tuesdays. But truthfully, when I’m in the middle of making a record, especially now when the world is in the middle of such a tumultuous period, I find I really need to take the space for myself far away from real life, to consider what my contribution to the world should be in these dark times. <br><br>So each morning, I have the luxury of asking myself, “What shall I cook up for the kids today? Something with a little spice? Something with a little bitterness but is ultimately sweet? Or shall I take the day off and turn down the fire, and just take a moment to send my love to them over the ether?” Because sometimes, just being pure of heart and having good intentions and letting them be known is the most worthy contribution an artist can make. So, even though these times can feel a little bit crazy, they’re not so very different from what other generations have experienced at one time or another before. Amidst all the uncertainty, and as we transition out of one era into another one, there’s no place I’d rather be than smack-dab in the middle of “Holly-weird” making this record for you. Because you, and the music, and this place, are my love, my life, my lust for life."﻿;
		}
}